name: release
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Check out code
        uses: actions/checkout@v1
      - name: Build
        run: make
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_PACKAGE_TOKEN }}
        run: |
          echo ${{ secrets.GITHUB_PACKAGE_TOKEN }} | docker login -u danielpacak --password-stdin docker.pkg.github.com
          curl -sL https://git.io/goreleaser | bash -s -- --rm-dist
